SELECT*FROM Orquestador;
CREATE TABLE DOMINIO(
ID_DOMINIO NUMBER PRIMARY KEY,
INFORMACION NVARCHAR2(255));

CREATE TABLE ORQUESTADOR (
ID_ORQUESTADOR NUMBER PRIMARY KEY,
INFORMACION NVARCHAR2(255));

drop table DOMINIO;